bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
model_class_filename: model.py
model_class_name: Model
model_framework: sklearn
model_metadata:
  model_binary_dir: model
  supports_predict_proba: true
model_module_dir: model
model_name: null
model_type: Model
python_version: py37
requirements:
- scipy==1.4.1
- numpy==1.21.6
- scikit-learn==0.22.1
- baseten==0.2.8
- joblib==0.14.1
- pandas==1.3.5
resources:
  cpu: 500m
  memory: 512Mi
  use_gpu: false
secrets: {}
spec_version: '2.0'
system_packages: []
